Search implementation
FUMR/music-service-async-interface pull request #31
Opened 2021-05-19 22:22 UTC by JuniorJPDJ

First implementation, to be verified by FUMR/tidal-async impl.
resolves #14

2021-05-19 22:46 UTC, wvffle requested changes

2021-05-19 22:46 UTC, wvffle commented on music_service_async_interface/__init__.py
> +    """Generic class to be subclassed by any searchable :class:`Object`
s/subclassed/extended/

2021-05-19 22:46 UTC, wvffle commented on music_service_async_interface/__init__.py
> +    Eg. if music service is abled to search for tracks and
s/Eg/For example/
s/d//

2021-05-19 22:46 UTC, wvffle commented on music_service_async_interface/__init__.py
> +    playlists, `Track` and `Playlist` classes should subclass this class.
s/subclass/extend/

2021-05-19 22:46 UTC, wvffle commented on music_service_async_interface/__init__.py
> +        """Searches music service for specific type(s) of :class:`Searchable` objects using `query`
either `types of objects` or `type of object`
s/query/query string/

if it refers to the Searchable class, then phrase it like: `Searches music service for specific Searchable types using....`

2021-05-19 22:46 UTC, wvffle commented on music_service_async_interface/__init__.py
> +        :param types: :class:`Searchable` object or list of objects, filters search results to this type,
Is it an object or a class type

2021-05-19 22:46 UTC, wvffle commented on music_service_async_interface/__init__.py
> +        eg. if you want to search for tracks use `sess.search('text', Track)`
s/eg./e. g./

2021-05-19 23:15 UTC, JuniorJPDJ commented on music_service_async_interface/__init__.py
> +        :param types: :class:`Searchable` object or list of objects, filters search results to this type,
oh fuck.

2021-05-23 03:31 UTC, wvffle requested changes

2021-05-23 03:31 UTC, wvffle commented on music_service_async_interface/__init__.py
> +        Also allows to search for all possible objects, then this parameter is left unset or set to None/empty list.
Same as in the tidal implementation

2021-05-23 03:31 UTC, wvffle commented on music_service_async_interface/__init__.py
> +    For example if music service is abled to search for tracks and
abled

2021-05-23 17:42 UTC, JuniorJPDJ commented
[T. Hanks](https://en.wikipedia.org/wiki/Tom_Hanks) for review @wvffle, is it fixed now?

2021-05-23 23:18 UTC, JuniorJPDJ commented
Just rebasing.

2021-05-24 00:00 UTC, wvffle approved these changes

2021-05-24 00:25 UTC, merged