Add linting configuration and fix linitng problems
FUMR/music-service-async-interface pull request #8
Opened 2020-09-01 11:28 UTC by wvffle

2020-09-01 15:29 UTC, JuniorJPDJ requested changes
The issues with this configuration are probably the same as in https://github.com/FUMR/tidal-async/pull/27.
Only one came up in this pull, but it will probably piss me off later XD
Tell me what do you think about things I stated in both issues please.

2020-09-01 15:29 UTC, JuniorJPDJ commented on music_service_async_interface/__init__.py
> +                await self.get_file_url(*args, **kwargs), self.title if filename is None else filename, self.sess.sess
uhm, I liked previous split, it's much more readable

2020-09-02 05:06 UTC, JuniorJPDJ commented
What do you think about creating template repository with this configs and some other project files like .gitignore, license or poetry project.
It would make creating new repositories way easier.

2020-09-02 05:07 UTC, JuniorJPDJ commented on music_service_async_interface/__init__.py
> +                await self.get_file_url(*args, **kwargs), self.title if filename is None else filename, self.sess.sess
Ok, now I know we just need a trailing coma to make this work as I want it to.
Could you please add it to this PR?

2020-09-02 06:28 UTC, wvffle commented
Yup I planned to do this today

2020-09-02 07:04 UTC, merged

2020-09-02 13:58 UTC, JuniorJPDJ reviewed
<3